apiVersion: v1
kind: Pod
metadata:
  labels:
    name: external
  name: external
spec:
  containers:
  - env:
    - name: APP_NAME
      value: External Facing Application
    - name: BG_COLOR
      value: red
    image: kodekloud/webapp-conntest
    imagePullPolicy: Always
    name: external
    ports:
    - containerPort: 8080
      protocol: TCP
    resources: {}
